[package]
name = "spartan"
version = "0.2.1"
authors = ["Srinath Setty <srinath@microsoft.com>"]
edition = "2018"
description = "High-speed zkSNARKs without trusted setup"
documentation = "https://docs.rs/spartan/"
readme = "README.md"
repository = "https://github.com/microsoft/Spartan"
license-file = "LICENSE"
keywords = ["zkSNARKs", "cryptography", "proofs"]

[dependencies]
merlin = "2.0.0"
digest = "0.9"
byteorder = "1.3.4"
rayon = "1.3.0"
serde = { version = "1.0.106", features = ["derive"] }
bincode = "1.2.1"
subtle = { version = "^2.2.3", default-features = false }
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }
zeroize = { version = "1", default-features = false }
itertools = "0.9.0"
colored = "1.9.3"
flate2 = "1.0.14"
thiserror = "1.0"
funty = "=1.1.0"
bitvec = "0.20"
ff = {version = "0.9", features = ["derive"]}
rand_chacha = "0.3"
ligero-pc = {path = "../ligero-pc"}
fffft = "*"
blake3 = "0.3"

[dev-dependencies]
criterion = "0.3.1"

[lib]
name = "libspartan"
path = "src/lib.rs"

[[bin]]
name = "snark"
path = "profiler/snark.rs"

[[bin]]
name = "nizk"
path = "profiler/nizk.rs"

[[bench]]
name = "snark"
harness = false

[[bench]]
name = "nizk"
harness = false

[features]
multicore = []
profile = []
